env = Environment(toolpath = ['../scons'], tools = ['default', 'oft_java'])
env.Append(JAVACFLAGS = ['-encoding', 'utf8', '-Xlint:deprecation', '-Xlint:unchecked'])

# add dependencies here
# env.AppendUnique(JAVACLASSPATH="/usr/share/java/bcel.jar")

manifest = env.Manifest(target='build/MANIFEST.MF', mainclass="Main")
app = env.JavaToJar('build/polymorphic_method_overloading.jar', ['src', 'build/MANIFEST.MF'])

env.Alias('app', app)
env.Alias('run', env.RunJar(app))

env.Default('app')
