env = Environment(toolpath = ['../scons/tools'], tools = ['default', 'java2jar'])
env.Append(JAVACFLAGS = ['-encoding', 'utf8', '-Xlint:deprecation', '-Xlint:unchecked'])

# add dependencies here
# env.AppendUnique(JAVACLASSPATH="/usr/share/java/bcel.jar")

manifest = env.Manifest(target='build/MANIFEST.MF', mainclass="events.Main")
app = env.JavaToJar('build/enums.jar', ['src', 'build/MANIFEST.MF'])


env.Alias('app', app)
env.Alias('run', env.RunJar(app))

env.Default('app')
